name: Build PR
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
        id: go

      - name: Check license headers
        run: make validate

      - name: Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . v1.51.1
          ./golangci-lint run

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      E2E_TEST_AUTH_TOKEN: ${{ secrets.E2E_TEST_AUTH_TOKEN }}
      E2E_HUB_URL: ${{ secrets.E2E_HUB_URL }}
      E2E_HUB_USERNAME: ${{ secrets.E2E_HUB_USERNAME }}
      E2E_HUB_TOKEN: ${{ secrets.E2E_HUB_TOKEN }}
    steps:
      - name: Docker version
        run: docker version

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
        id: go

      - name: Build binary
        run: make TAG_NAME=${{ github.event.inputs.tag }} -f builder.Makefile build

      - name: Build Cross
        run: make cross

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-scan
          path: ./dist/
